# docker-compose file for development:
version: '3.8'

services:
  api:
    build: '.'
    ports:
      - '8000:8000'
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes:
      - db_volume:/var/lib/postgresql

volumes:
  db_volume:
