@startuml usecases

left to right direction

actor User

rectangle Todostateful {
  rectangle TaskList as "Task list" {
    usecase ViewTaskLists as "View task lists" #LightBlue
    usecase CreateTaskList as "Create task list" #LightBlue
    usecase EditTaskList as "Edit task list" #LightBlue
    usecase DeleteTaskList as "Delete task list" #LightBlue
  }

  note right of TaskList
    There is always a default
    task list, which can't be deleted
  end note

  rectangle Task {
    usecase ViewAllTasks as "View all tasks in list" #LightBlue
    usecase CreateTask as "Create new task" #LightBlue
    usecase EditTask as "Edit task" #LightBlue
    usecase DeleteTask as "Delete task" #LightBlue
    usecase CompleteTask as "Complete task" #LightBlue
    usecase UnCompleteTask as "Uncomplete task" #LightBlue
  }

  rectangle Calendar {
    usecase PickTime as "Pick due time" #Pink
    usecase SetToRepeat as "Set to repeat" #Pink
  }
}

User -- Todostateful

ViewTaskLists <.. CreateTaskList: extends
ViewTaskLists <.. EditTaskList: extends
ViewTaskLists <.. DeleteTaskList: extends
ViewTaskLists <. ViewAllTasks: extends

ViewAllTasks <.. CreateTask: extends
ViewAllTasks <.. EditTask: extends
ViewAllTasks <.. DeleteTask: extends
ViewAllTasks <.. CompleteTask: extends
ViewAllTasks <.. UnCompleteTask: extends

CreateTask <. Calendar: extends
EditTask <.. Calendar: extends

@enduml
